Feat: Controller 구현 [#24]
prgrms-be-devcourse/BE-04-CREAM pull request #25
Opened 2023-09-03 03:57 UTC by kju2405

- 코드리뷰 반영 및 도메인별 등록 수정 삭제 조회 기능을 수행하는 컨트롤러를 구현하였습니다.
- 컨트롤러 테스트 코드 작성을 직접 해보는것은 처음이라 검토 부탁드립니다.
- 커밋을 rebase하는 과정에서 merge된 커밋이 있어서 rebae가 되지 않았습니다. 어제도 이와 같은 과정을 겪어서 많은 검색과 시도 끝에 결국 새로운 branch를 파서 다시 작업하였으나 오늘 또 이러한 상황이 발생하였습니다. 혹시 시간되실때 도와주시면 감사하곘습니다. 죄송합니다.

2023-09-03 07:14 UTC, BeomSeogKim commented
혹시 [9b2438d] 와 [5bbe856]의 커밋에 어떤 차이가 있는건가요 
기능적으로 큰 차이가 있지 않다면 `rebase`전략을 지켜주세요

2023-09-03 07:38 UTC, legowww commented on src/main/java/com/programmers/dev/kream/product/application/BrandService.java
> +            .orElseThrow(() -> new NoSuchElementException("해당 브랜드는 존재하지 않습니다."));
더 적절한 예외인 EntityNotFoundException 을 사용하는게 좋아보입니다

2023-09-03 07:39 UTC, BeomSeogKim requested changes
코멘트 참고해주세요

2023-09-03 07:39 UTC, BeomSeogKim commented on src/main/java/com/programmers/dev/kream/product/application/BrandService.java
> +                    });
해당 부분의 경우 
기능과 구현이 같이 있어 조금 이해하기 어려울 수 있다는 생각이 드네요. 
```
sizedProductRepository.findAll()
                    .forEach(sizedProduct -> {
                        if (sizedProduct.getProduct().getBrand() == brand) {
    sizedProductRepository.delete(sizedProduct);
}
});
```
이런 코드들은 deleteProduct라는 메서드로 빼도 좋을 것 같아요

추가적으로 if 문이 존재하는데 해당 부분같은 경우에는 처음부터 query를 날릴 때 조건문을 포함시켜서 query를 날리면 좋지 않을까 싶네요. 
(쿼리로 100개의 데이터를 가져와서 검증하는 것 보다는 10개의 데이터만 들고오는게 좋지 않을까요?)

2023-09-03 07:39 UTC, BeomSeogKim commented on src/main/java/com/programmers/dev/kream/product/application/BrandService.java
>              .orElseThrow(() -> new NoSuchElementException("해당 브랜드는 존재하지 않습니다."));
해당 부분도 메서드로 빼면 좋을 것 같아요

2023-09-03 07:39 UTC, BeomSeogKim commented on src/main/java/com/programmers/dev/kream/product/ui/BrandController.java
> +            .body(Collections.singletonMap("brandName", brandSaveRequest.name()));
해당 부분의 경우 singleton map 보다는 record를 사용하면 좋을 것 같습니다.

2023-09-03 07:39 UTC, BeomSeogKim commented on src/test/java/com/programmers/dev/kream/product/application/BrandServiceTest.java
>          assertThatThrownBy(() -> brandService.findByName(brandName)).isInstanceOf(NoSuchElementException.class);
그냥 findAll로 조회해오고 Empty로 검증하는 것이 좋아보입니다. 
결국엔 명세화 하고 싶은게 데이터가 없다니까?

2023-09-03 07:39 UTC, legowww commented on src/main/java/com/programmers/dev/kream/product/ui/ProductController.java
> +
ProductSaveRequest 객체 하나로 파라미터로 사용해도 될 것 같아요

2023-09-03 07:43 UTC, legowww commented on src/main/java/com/programmers/dev/kream/product/ui/dto/ListResponse.java
> +}
저는 ListResponse 라는 이름만 보고는 어떤 값을 반환할지 유추하기 힘드네요

2023-09-03 07:52 UTC, legowww reviewed
테스트에서 .content(objectMapper.writeValueAsString())
를 쓰셨다 안쓰셨다 하는데 어떤 기준이 있을까요? 

컨트롤러를 Mock 객체로 사용하신다면 적어도 given() 정도는 사용하는게 좋을 듯 합니다. 
BDDMockito.given 클래스의 메서드입니다.

2023-09-03 07:58 UTC, legowww commented on src/main/java/com/programmers/dev/kream/product/application/BrandService.java
> +                    });
저도 범석님과 동일하게 생각합니다. 스트림 내에서 구현하지 말고 이미 정의된 기능을 사용하도록 수정하셨으면 좋겠네요

2023-09-03 08:20 UTC, legowww commented on src/main/java/com/programmers/dev/kream/product/ui/ProductController.java
> +    }
반환값에 생성된 product 식별자도 추가하면 좋을 것 같습니다!

2023-09-03 08:40 UTC, legowww commented on src/test/java/com/programmers/dev/kream/product/ui/BrandControllerTest.java
> +        resultActions.andExpect(status().isCreated());
현재 테스트는 요청값이 JSON인,  응답이 CREATED 인지 검증하는데, 그 외에도 mockMvc 가 반환하는 응답하는 객체에 대한 검증도 추가해보면 좋을 것 같습니다.

2023-09-03 08:55 UTC, legowww commented on src/test/java/com/programmers/dev/kream/product/ui/BrandControllerTest.java
> +        resultActions.andExpect(status().isCreated());
andExpect 에서 content() 검증도 해주면 좋을 것 같아요

2023-09-04 04:54 UTC, kju2405 commented on src/main/java/com/programmers/dev/kream/product/application/BrandService.java
> +                    });
양방향 연관관계 매핑을 해주고 cascade로 해결하는 방법을 시도. -> 성공
하지만 SizedProducts 테이블의 데이터를 삭제할 경우 입찰 테이블과의 정합성 문제가 발생할 여지가 있음 -> 브랜드 삭제 기능을 제거.

2023-09-04 08:44 UTC, kju2405 commented on src/test/java/com/programmers/dev/kream/product/application/BrandServiceTest.java
>          assertThatThrownBy(() -> brandService.findByName(brandName)).isInstanceOf(NoSuchElementException.class);
그렇게 테스트하는 방법은 생각하지 못했네요 감사합니다!
해당 부분은 삭제 기능을 제거하면서 테스트도 제거하였습니다!

2023-09-04 08:48 UTC, kju2405 commented on src/main/java/com/programmers/dev/kream/product/ui/dto/ListResponse.java
> +}
모든 product, brand들을 조회할때 사용하는 Dto이기 때문에 각각 BrandsGetResponse, ProductsGetResponse record를 작성하였고 안에 데이터는 고도화해나가며 필요한 데이터들을 넣을 예정입니다.
혹시 이와 같은 네이밍은 보다 더 직관적일까요???

2023-09-04 22:59 UTC, BeomSeogKim approved these changes
수고하셨습니다!

2023-09-05 02:02 UTC, legowww approved these changes
test 코드 잘 작성해주셨습니다!

2023-09-05 04:01 UTC, merged